version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
            - "80:443"
            - "587:587"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/web"
        depends_on:
            - "php"
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/web
    composer:
        image: composer
        volumes:
            - ./web/app:/app
        command: install